### ISSUE TITLE
User inputs ignored?

### ISSUE THREAD

**Issue by kaselis** [dwolfhub/zxcvbn-python#18]
I've replaced original library (from dropbox) with this one and couple of my tests started to fail. On inspection it seems that user inputs are being ignored:

    >>> zxcvbn('JohnSmith123')['score']
    2
    >>> zxcvbn('JohnSmith123', ['John', 'Smith'])['score']
    2
I've expected to get 0 on the second one. Note, both examples return 0 in the original library.

**Comment by dwolfhub** [comment]
This library and the JS one, which is in active development by Dropbox, have been tested against each other using 1M passwords. The logic matches, and in fact I've been told they are using this lib in production server side.

If you are coming from the older python library, it's definitely not going to match, because the logic has been updated by the Dropbox team since then.

I can see why you'd be concerned with that example. I promise that the user input is being used.

```
>>> zxcvbn('johnsmith123', ['johnsmith123'])['score']
>>> 0
>>> zxcvbn('johnsmith123')['score']
>>> 2
```

I did not develop the logic that this library uses. I simply ported it from JS. If you feel like maybe the logic is flawed, definitely post something in the JS library Github repo. Unfortunately I don't think I can help you.

Cheers
