### ISSUE TITLE
apply to take over pypi/zxcvbn

### ISSUE THREAD

**Issue by graingert** [dwolfhub/zxcvbn-python#23]

**Comment by graingert** [comment]
@dwolfhub See also https://www.python.org/dev/peps/pep-0541/

**Comment by dwolfhub** [comment]
hey thanks for your help on this. 

i looked into it before, but no one at dropbox really knew who was in control of that repo and no one really responded on github.

i don't think applying through pypi would work because that current library still has people using it, so it doesn't qualify for a takeover. correct me if i'm wrong.

i'll monitor this and if there is anything i need to do just @ me.

thanks again

**Comment by graingert** [comment]
Ah the new policy PEP applies in this case, and if you look at the issue on
dropbox's GitHub I managed to contact the actually PyPI owner

**Comment by graingert** [comment]
@dwolfhub the package owner is @rpearl
