### ISSUE TITLE
Release notes / changelog

### ISSUE THREAD

**Issue by rixx** [dwolfhub/zxcvbn-python#38]
Does this project have any release notes or a running changelog? I prefer to look at some documentation before updating a package.

**Comment by dwolfhub** [comment]
Hey @rixx 

We don't have a running changelog. This project was released after 4.4 came out for the JS version and we haven't released anything but a patch since, so there hasn't really been a need for one. 

In the future, if the Dropbox team decides to make upgrades to the library, I'll follow suit and be sure to document them.
