### ISSUE TITLE
OverflowError for long random passwords

### ISSUE THREAD

**Issue by barredterra** [dwolfhub/zxcvbn-python#69]
```
>>> from zxcvbn import zxcvbn
>>> import random
>>> import string
>>> password = ''.join(random.choice(string.printable) for i in range(400))
>>> zxcvbn(password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python3.8/site-packages/zxcvbn/__init__.py", line 31, in zxcvbn
    result = scoring.most_guessable_match_sequence(password, matches)
  File "env/lib/python3.8/site-packages/zxcvbn/scoring.py", line 200, in most_guessable_match_sequence
    bruteforce_update(k)
  File "env/lib/python3.8/site-packages/zxcvbn/scoring.py", line 160, in bruteforce_update
    update(m, l + 1)
  File "env/lib/python3.8/site-packages/zxcvbn/scoring.py", line 117, in update
    pi *= optimal['pi'][m['i'] - 1][l - 1]
OverflowError: int too large to convert to float
```

The length where this breaks varies depending on the password, so you might have to try multiple times or with more than 400 characters.

Version tested: 4.4.24

**Comment by barredterra** [comment]
Duplicate of #34

**Comment by Tostino** [comment]
So I haven't checked your implementation directly...however there have been some reports of DOS exploits from users of my library due to specially crafted passwords. I found a specific implementation of this:https://github.com/twosixlabs/acsploit/blob/fd5602adf9f312482b8010abf6b4691f08929bc4/acsploit/exploits/passwords/zxcvbn.py

For example, here is just 100 characters of their crafted password in the default implementation:
![image](https://user-images.githubusercontent.com/8227578/214922642-7e14bde5-4f67-4040-ab57-3da2dbf20d21.png)

**Comment by barredterra** [comment]
@Tostino, interesting! You should probably create a separate issue for this, as it will most certainly get no attention in this closed thread.

**Comment by Tostino** [comment]
I don't know what I was thinking here... I opened a new issue for this on every other repo I have warned today, but this is the only one I didn't do that for.  Will do.
